#!/usr/bin/env perl

######################################################################
#2006-06-26                                                          #
#Sebastien MORETTI, moretti.sebastien [AT] gmail.com, SIB            #
#Olivier POIROT, poirot [AT] igs.cnrs-mrs.fr, Labo IGS, UPR2589      #
#Web interface for Tcoffee and other programs                        #
#Need feedback.cgi, configuration_file.txt                           #
######################################################################

use strict;
use warnings;
use diagnostics;

use IP::Country::Fast;

my %country = (
AD => 'Andorra',
AE => 'United Arab Emirates',
AF => 'Afghanistan',
AG => 'Antigua and Barbuda',
AI => 'Anguilla',
AL => 'Albania',
AM => 'Armenia',
AN => 'Netherland Antilles',
AO => 'Angola',
AQ => 'Antarctica',
AR => 'Argentina',
AS => 'American Samoa',
AT => 'Austria',
AU => 'Australia',
AW => 'Aruba',
AZ => 'Azerbaidjan',
BA => 'Bosnia-Herzegovina',
BB => 'Barbados',
BD => 'Banglades',
BE => 'Belgium',
BF => 'Burkina Faso',
BG => 'Bulgaria',
BH => 'Bahrain',
BI => 'Burundi',
BJ => 'Benin',
BM => 'Bermuda',
BN => 'Brunei Darussalam',
BO => 'Bolivia',
BR => 'Brazil',
BS => 'Bahamas',
BT => 'Buthan',
BV => 'Bouvet Island',
BW => 'Botswana',
BY => 'Belarus',
BZ => 'Belize',
CA => 'Canada',
CC => 'Cocos (Keeling) Islands',
CF => 'Central African Republic',
CG => 'Congo',
CH => 'Switzerland',
CI => 'Ivory Coast',
CK => 'Cook Islands',
CL => 'Chile',
CM => 'Cameroon',
CN => 'China',
CO => 'Colombia',
CR => 'Costa Rica',
CS => 'Czechoslovakia',
CU => 'Cuba',
CV => 'Cape Verde',
CX => 'Christmas Island',
CY => 'Cyprus',
CZ => 'Czech Republic',
DE => 'Germany',
DJ => 'Djibouti',
DK => 'Denmark',
DM => 'Dominica',
DO => 'Dominican Republic',
DZ => 'Algeria',
EC => 'Ecuador',
EE => 'Estonia',
EG => 'Egypt',
EH => 'Western Sahara',
ES => 'Spain',
ET => 'Ethiopia',
FI => 'Finland',
FJ => 'Fiji',
FK => 'Falkland Islands (Malvinas)',
FM => 'Micronesia',
FO => 'Faroe Islands',
FR => 'France',
FX => 'France (European Territory)',
GA => 'Gabon',
GB => 'Great Britain (UK)',
GD => 'Grenada',
GE => 'Georgia',
GH => 'Ghana',
GI => 'Gibraltar',
GL => 'Greenland',
GP => 'Guadeloupe (French)',
GQ => 'Equatorial Guinea',
GF => 'Guyana (French)',
GM => 'Gambia',
GN => 'Guinea',
GR => 'Greece',
GT => 'Guatemala',
GU => 'Guam (US)',
GW => 'Guinea Bissau',
GY => 'Guyana',
HK => 'Hong Kong',
HM => 'Heard and McDonald Islands',
HN => 'Honduras',
HR => 'Croatia',
HT => 'Haiti',
HU => 'Hungary',
ID => 'Indonesia',
IE => 'Ireland',
IL => 'Israel',
IN => 'India',
IO => 'British Indian Ocean Territory',
IQ => 'Iraq',
IR => 'Iran',
IS => 'Iceland',
IT => 'Italy',
JM => 'Jamaica',
JO => 'Jordan',
JP => 'Japan',
KE => 'Kenya',
KG => 'Kirgistan',
KH => 'Cambodia',
KI => 'Kiribati',
KM => 'Comoros',
KN => 'Saint Kitts Nevis Anguilla',
KP => 'North Korea',
KR => 'South Korea',
KW => 'Kuwait',
KY => 'Cayman Islands',
KZ => 'Kazachstan',
LA => 'Laos',
LB => 'Lebanon',
LC => 'Saint Lucia',
LI => 'Liechtenstein',
LK => 'Sri Lanka',
LR => 'Liberia',
LS => 'Lesotho',
LT => 'Lithuania',
LU => 'Luxembourg',
LV => 'Latvia',
LY => 'Libya',
MA => 'Morocco',
MC => 'Monaco',
MD => 'Moldavia',
MG => 'Madagascar',
MH => 'Marshall Islands',
ML => 'Mali',
MM => 'Myanmar',
MN => 'Mongolia',
MO => 'Macau',
MP => 'Northern Mariana Islands',
MQ => 'Martinique (French)',
MR => 'Mauritania',
MS => 'Montserrat',
MT => 'Malta',
MU => 'Mauritius',
MV => 'Maldives',
MW => 'Malawi',
MX => 'Mexico',
MY => 'Malaysia',
MZ => 'Mozambique',
NA => 'Namibia',
NC => 'New Caledonia (French)',
NE => 'Niger',
NF => 'Norfolk Island',
NG => 'Nigeria',
NI => 'Nicaragua',
NL => 'Netherlands',
NO => 'Norway',
NP => 'Nepal',
NR => 'Nauru',
NT => 'Neutral Zone',
NU => 'Niue',
NZ => 'New Zealand',
OM => 'Oman',
PA => 'Panama',
PE => 'Peru',
PF => 'Polynesia (French)',
PG => 'Papua New',
PH => 'Philippines',
PK => 'Pakistan',
PL => 'Poland',
PM => 'Saint Pierre and Miquelon',
PN => 'Pitcairn',
PT => 'Portugal',
PR => 'Puerto Rico (US)',
PW => 'Palau',
PY => 'Paraguay',
QA => 'Qatar',
RE => 'Reunion (French)',
RO => 'Romania',
RU => 'Russian Federation',
RW => 'Rwanda',
SA => 'Saudi Arabia',
SB => 'Solomon Islands',
SC => 'Seychelles',
SD => 'Sudan',
SE => 'Sweden',
SG => 'Singapore',
SH => 'Saint Helena',
SI => 'Slovenia',
SJ => 'Svalbard and Jan Mayen Islands',
SK => 'Slovak Republic',
SL => 'Sierra Leone',
SM => 'San Marino',
SN => 'Senegal',
SO => 'Somalia',
SR => 'Suriname',
ST => 'Saint Tome and Principe',
SU => 'Soviet Union',
SV => 'El Salvador',
SY => 'Syria',
SZ => 'Swaziland',
TC => 'Turks and Caicos Islands',
TD => 'Chad',
TF => 'French Southern Territory',
TG => 'Togo',
TH => 'Thailand',
TJ => 'Tadjikistan',
TK => 'Tokelau',
TM => 'Turkmenistan',
TN => 'Tunisia',
TO => 'Tonga',
TP => 'East Timor',
TR => 'Turkey',
TT => 'Trinidad and Tobago',
TV => 'Tuvalu',
TW => 'Taiwan',
TZ => 'Tanzania',
UA => 'Ukraine',
UG => 'Uganda',
UK => 'United Kingdom',
UM => 'US Minor Outlying Islands',
US => 'United States',
UY => 'Uruguay',
UZ => 'Uzbekistan',
VA => 'Vatican City State',
VC => 'Saint Vincent and Grenadines',
VE => 'Venezuela',
VG => 'Virgin Islands (British)',
VI => 'Virgin Islands (US)',
VN => 'Vietnam',
VU => 'Vanuatu',
WF => 'Wallis and Futuna Islands',
WS => 'Samoa',
YE => 'Yemen',
YU => 'Yugoslavia',
ZA => 'South Africa',
ZM => 'Zambia',
ZR => 'Zaire',
ZW => 'Zimbabwe',
);

my $reg      = IP::Country::Fast->new();
my @tab_res;
my $ip2check = join('', @ARGV) || '';
$ip2check    =~ s/\ +//g;
my @IPs      = split(',', $ip2check);
ADD_IP:
foreach my $une_ad (@IPs){
    $une_ad =~ s\,\\;
    if( $une_ad ne 'unknown' && defined($reg->inet_atocc($une_ad)) && $reg->inet_atocc($une_ad) ne '**' && $une_ad =~ /^\d+\.\d+\.\d+/ ) {
        push @tab_res, $country{$reg->inet_atocc($une_ad)} || '**';
    }
    else {
        push @tab_res, '**';
    }
}
print join (', ', @tab_res)."\n" if ( defined($tab_res[0]) );
exit(0);

